---
".travis.yml":
  deploy_to_forge:
    enabled: false
  secure: ''
  bundler_args: ''
  remove_branches:
    - master
    - /^v\d/
  simplecov: true
  use_litmus: true
  litmus:
    provision_list:
    - ---travis_el
    - travis_deb
    - travis_el6
    - travis_el7
    - travis_el8
    complex:
    - collection:
        puppet_collection:
        - puppet6
        provision_list:
        - travis_ub_6
    - collection:
        puppet_collection:
        - puppet5
        provision_list:
        - travis_ub_5

appveyor.yml:
  delete: true

".gitlab-ci.yml":
  delete: true

Gemfile:
  optional:
    ':development':
      - gem: 'serverspec'
      - gem: 'hiera-puppet-helper'

Rakefile:
  requires:
  - puppet-lint/tasks/puppet-lint

spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
