---
".travis.yml":
  use_litmus: true
  beaker: true
  deploy_to_forge:
    enabled: false
  secure: ''
  bundler_args: ''
  remove_branches:
    - master
    - /^v\d/
  simplecov: true

appveyor.yml:
  delete: true

".gitlab-ci.yml":
  delete: true

Gemfile:
  optional:
    ':development':
      - gem: 'serverspec'
      - gem: 'hiera-puppet-helper'
      - gem: 'beaker'
      - gem: 'beaker-rspec'

Rakefile:
  requires:
  - puppet-lint/tasks/puppet-lint

spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
